new changes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,11 +45,11 @@ jobs:
       - image: circleci/node:13.8.0
     steps:
       - run : 
-        command: |
-          echo "Error On the build.............."
-          exit 125
+          command: |
+            echo "Error On the build.............."
+            exit 125
       - run: echo "This step ran because their was a failure on the job"
-        when: on_fail
+          when: on_fail
 
 
 workflows:
